import type { Metadata } from "next";
import "./globals.css";
import { FooterComponent } from "@/src/components/FooterComponent";


export const metadata: Metadata = {
  title: "HDI Gmbh Demontagen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        {children}
        <FooterComponent/>
      </body>
    </html>
  );
}
